# Generated by Django 4.0.2 on 2022-03-10 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_testmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 10, 14, 12, 30, 883896)),
        ),
    ]
