# Generated by Django 4.0.2 on 2022-02-26 18:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grp_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grppost',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 26, 18, 16, 52, 560156, tzinfo=utc)),
        ),
    ]
