# Generated by Django 4.0.2 on 2022-02-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_alter_group_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='group/grp_icons'),
        ),
    ]
