# Generated by Django 4.0.2 on 2022-02-28 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_post_no_of_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0005_group_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAdminship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_made_admin', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='grp_admins',
            field=models.ManyToManyField(related_name='admins', through='group.GroupAdminship', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='members', through='group.GroupMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupadminship',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminships', to='group.group'),
        ),
        migrations.AddField(
            model_name='groupadminship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='groupadminship',
            unique_together={('user', 'group')},
        ),
    ]
