# Generated by Django 4.0.2 on 2022-03-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_groupadminship_group_grp_admins_alter_group_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='no_of_admins',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='no_of_members',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
