# Generated by Django 4.0.2 on 2022-03-02 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_group_no_of_admins_group_no_of_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.date(2022, 3, 2)),
        ),
    ]
