# Generated by Django 4.0.2 on 2022-03-10 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_group_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.date(2022, 3, 10)),
        ),
    ]
