# Generated by Django 4.0.2 on 2022-02-26 11:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_day_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='day_added',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 2, 26, 11, 38, 42, 649639, tzinfo=utc)),
        ),
    ]
