# Generated by Django 4.0.2 on 2022-02-26 11:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_day_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='day_added',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 2, 26, 11, 40, 48, 97858, tzinfo=utc)),
        ),
    ]
