# Generated by Django 4.0.2 on 2022-02-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_day_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='day_added',
            field=models.DateField(auto_now=True),
        ),
    ]
