# Generated by Django 4.0.2 on 2022-02-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_post_likers_post_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='no_of_likes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
